### ISSUE TITLE
Leo-Eligible inconsistency

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/Marpa-arxiv-paper#10]
```
  Leo-Eligible(xDR,currentLOC) ≝ ...

 LIMT-Predecessor(predLIMT, bottomEIMT) 
predLIMT =[predDR,LHS(bottomDR),predORIG]
     bottomEIMT = [bottomDR,bottomLOC]
           bottomEIMT ∈ currentES
           Leo-Eligible(bottomDR)
       -------------------------
   {[predDR, Penult(bottomDR), predORIG]}

 ¬LIMT-Predecessor(predLIMT, bottomEIMT) 
    bottomEIMT =[bottomDR,bottomORIG] 
         bottomEIMT ∈ currentES
          Leo-Eligible(bottomDR)
  ----------------------------------------
{[Next(bottomDR), Penult(bottomDR), bottomORIG]}
```

The invocations of Leo-Eligible don't seem to match its signature.

**Comment by jeffreykegler** [comment]
@dabrahams -- I am getting back to theseissues on the arxiv paper.  It's been quite a while I know, but when I have dozens of issues, many of which are complicated, I remember the advice about how to eat an elephant: one bite at a time.

**Comment by jeffreykegler** [comment]
Fixed by commits https://github.com/jeffreykegler/Marpa-arxiv-paper/commit/1f907419a6ee5f83946df71068a27229c169383d and https://github.com/jeffreykegler/Marpa-arxiv-paper/commit/de25bea26bd91cda4e672698e875061a0620bb9f.  Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/Marpa-arxiv-paper/issues/10#issuecomment-1236163458.
